### ISSUE TITLE
Is there a way to luanch JNLP applications using UI Automation API?

### ISSUE THREAD

**Issue by ndass-sapient** [mmarquee/ui-automation#63]
@markhumphreysjhc @pbi-qfs @mmarquee 

Hi guys,

I was able to launch a notepad application on Windows 10 using this API, but when I tried to launch a JNLP using same code (by replacing notepad.exe with path/url to JNLP file) I get below error. Thanks in advance.

Exception in thread "main" java.io.IOException: Cannot run program "C:\Users\adi\Downloads\Diva.jnlp" (in directory "C:\Users\adi\Downloads"): CreateProcess error=193, %1 is not a valid Win32 application
 at java.lang.ProcessBuilder.start(Unknown Source)
 at mmarquee.automation.utils.Utils.startProcessWithWorkingDirectory(Utils.java:135)
 at mmarquee.automation.UIAutomation.launchWithDirectory(UIAutomation.java:162)
 at mmarquee.automation.UIAutomation.launchWithWorkingDirectoryOrAttach(UIAutomation.java:215)
 at com.mkyong.TestJnlp.main(TestJnlp.java:38)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
 at java.lang.ProcessImpl.create(Native Method)
 at java.lang.ProcessImpl.<init>(Unknown Source)
 at java.lang.ProcessImpl.start(Unknown Source)
 ... 5 more

**Comment by pbi-qfs** [comment]
ui-automation library is made to test executables. A JNLP file is a file, and as thus not executable. The program to run this file is java(w), which you might have a success starting with the jnlp file as parameter. But as said in a comment in #52, to control java software (especially AWT/Swing based), a dedicated Java testing (= controlling) tool might be the better way to go.

**Comment by mmarquee** [comment]
I have tried to look at a Swing program via the UIA Explorer, and it is opaque, and as such the ms-automation API is not going to work with automating Swing programs.

**Comment by ndass-sapient** [comment]
Thanks @pbi-qfs & @mmarquee
