### ISSUE TITLE
Test failure  root: Not set

### ISSUE THREAD

**Issue by sirajka** [mmarquee/ui-automation#84]
Hello,

I am getting the following error during build (Windows 10 build 17134. I would appreciate any help!

`testGetFullDescription(mmarquee.automation.AutomationElementTest)  Time elapsed: 0.023 sec  <<< FAILURE!
java.lang.AssertionError: root:Not set
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at mmarquee.automation.AutomationElementTest.testGetFullDescription(AutomationElementTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
`

**Comment by mmarquee** [comment]
Hi, is this from running the unit tests?

**Comment by sirajka** [comment]
Yes. from running the unit tests.

Here is the test 
`	@Test
	public void testGetFullDescription() throws AutomationException {
		AutomationElement root = instance.getRootElement();
		assertTrue("root:" + root.getFullDescription(), root.getFullDescription().isEmpty());
	}`

And here is the method
`    /**
     * Gets the full description for the element, by trying to get the IUIAutomationElement6.
     *
     * Not supported in before Windows 10 build 1703
     * @return The description, if set
     * @throws AutomationException Something has gone wrong in automation library
     */
    public String getFullDescription() throws AutomationException {
        IUIAutomationElement6 element = this.getElement6();

        PointerByReference sr = new PointerByReference();

        final int res = element.getCurrentFullDescription(sr);

        if (res != 0) {
            throw new AutomationException(res);
        } else {
            if (sr.getValue() == null) {
                return "Not set";
            } else {
                return sr.getValue().getWideString(0);
            }
        }
    }`


The assert will never be true, right? As it will return either "Not set" or a value.

**Comment by mmarquee** [comment]
OK, I am now getting the same error - I wonder if something has changed in the latest Windows build. I will investigate further over the weekend.

**Comment by mmarquee** [comment]
No, I just have actually broken the tests for that API - these tests are tied to Windows, so don't automatically get run by the PR checks.  Should be fixed in the `develop` branch and the next snapshot (which I am doing today)

**Comment by sirajka** [comment]
I see the assert is now 
`assertTrue("root:" + root.getFullDescription(), root.getFullDescription().equals("Not set"))`

and method has 
```
            if (sr.getValue() == null) {
                return "Not set";
            } else {
                return sr.getValue().getWideString(0);
            }
```
Does this mean the `else` part will never be true

**Comment by mmarquee** [comment]
I have now retested the builds and all looks OK in both the 'master' and 'develop' branches. Will close this issue
