### ISSUE TITLE
Ui-automation is not working on win7

### ISSUE THREAD

**Issue by techshashank80** [mmarquee/ui-automation#96]
Hi,
I was trying to automate but I am getting an error on the first line.
UIAutomation automation=UIAutomation.getInstance();

Following errors are coming:
java.lang.NoSuchMethodError: com.sun.jna.platform.win32.Guid$GUID.createFieldsOrder([Ljava/lang/String;)Ljava/util/List;
	at com.sun.jna.platform.win32.Guid$GUID.<clinit>(Guid.java:108)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy10.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
	at com.sun.jna.Native.loadLibrary(Native.java:415)
	at com.sun.jna.platform.win32.Ole32.<clinit>(Ole32.java:47)
	at mmarquee.automation.Ole32Wrapper.createWrapper(Ole32Wrapper.java:65)
	at mmarquee.automation.Ole32Wrapper.<init>(Ole32Wrapper.java:58)
	at mmarquee.automation.UIAutomation.<init>(UIAutomation.java:86)
	at mmarquee.automation.UIAutomation.getInstance(UIAutomation.java:147)
	

OS: Win7
UI-automation version is Snapshot version .0.5.1
JDK: 1.8.0_121

however its working fine on Win10.

Thanks

**Comment by techshashank80** [comment]
Duplicate issue #52
